spring:
  application:
    name: job-service
  datasource:
    url: jdbc:postgresql://localhost:5432/job
    username: arun
    password: arun
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8080/  # Optional Config Server
  profiles:
    active: dev

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka  # Eureka server URL
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
    health:
      show-details: always

resilience4j:
  ratelimiter:
    instances:
      companyBreaker:
        timeout-duration: 0
        limit-refresh-period: 4
        limit-for-period: 2
  circuitbreaker:
    instances:
      companyBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        register-health-indicator: true
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based

job-service:
  url: http://localhost:8082  # Job service URL

company-service:
  url: http://localhost:8087  # Company service URL

review-service:
  url: http://localhost:8083  # Review service URL
